import {
  Plane,
  Watch,
  Briefcase,
  Building2,
  Car,
  Bell,
  Glasses,
  Anchor,
  Key,
  UtensilsCrossed,
  HeartPulse,
  Palette,
  CarFront,
  Shield,
  Wine,
  ChefHat,
  GraduationCap,
  Landmark,
  Plus,
  MessageSquare,
  Clock,
  CheckCircle2,
  XCircle,
  AlertCircle,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  User,
  Settings,
  LogOut,
  Moon,
  Sun,
  Menu,
  X,
  Search,
  Send,
  Loader2,
  Home,
  FileText,
  Users,
  LayoutDashboard,
  Calendar,
  ShoppingBag,
  type LucideIcon,
} from 'lucide-react'

export const categoryIcons: Record<string, LucideIcon> = {
  plane: Plane,
  watch: Watch,
  briefcase: Briefcase,
  building: Building2,
  car: Car,
  'concierge-bell': Bell,
  glasses: Glasses,
  anchor: Anchor,
  key: Key,
  utensils: UtensilsCrossed,
  'heart-pulse': HeartPulse,
  palette: Palette,
  'car-front': CarFront,
  shield: Shield,
  wine: Wine,
  'chef-hat': ChefHat,
  'graduation-cap': GraduationCap,
  landmark: Landmark,
  calendar: Calendar,
  'shopping-bag': ShoppingBag,
  'file-text': FileText,
  users: Users,
}

export function getCategoryIcon(iconName: string): LucideIcon {
  return categoryIcons[iconName] || Bell
}

export {
  Plus,
  MessageSquare,
  Clock,
  CheckCircle2,
  XCircle,
  AlertCircle,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  User,
  Settings,
  LogOut,
  Moon,
  Sun,
  Menu,
  X,
  Search,
  Send,
  Loader2,
  Home,
  FileText,
  Users,
  LayoutDashboard,
  Shield,
  Bell,
  Calendar,
  ShoppingBag,
}
